# Generated by Django 4.0.1 on 2022-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0002_alter_tableindi_numsemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='numSemana',
            field=models.IntegerField(),
        ),
    ]
