# Generated by Django 4.0.3 on 2022-03-20 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0003_alter_tableindi_numsemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableindi',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
