# Generated by Django 4.0.3 on 2022-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0005_alter_tableindi_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
