# Generated by Django 4.0.3 on 2022-03-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0006_alter_tableindi_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableindi',
            name='semana1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableindi',
            name='semana2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableindi',
            name='semana3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableindi',
            name='semana4',
            field=models.IntegerField(default=0),
        ),
    ]
