# Generated by Django 4.0.3 on 2022-03-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0007_tableindi_semana1_tableindi_semana2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='Razon',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
