# Generated by Django 4.0.3 on 2022-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0008_alter_tableindi_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableindi',
            name='mes',
            field=models.CharField(default=3, max_length=50),
        ),
    ]
