# Generated by Django 4.0.1 on 2022-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0009_tableindi_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableindi',
            name='mes',
        ),
    ]
