# Generated by Django 4.0.3 on 2022-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_clasificacion_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
