# Generated by Django 4.0.3 on 2022-03-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flujo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujoefec',
            old_name='categoria',
            new_name='id_categoria',
        ),
    ]
