# Generated by Django 4.0.3 on 2022-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flujo', '0004_alter_flujoefec_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoefec',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
