# Generated by Django 4.0.3 on 2022-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flujo', '0006_alter_flujoefec_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujoefec',
            name='mes',
            field=models.CharField(default=3, max_length=50),
        ),
    ]
